DELETE FROM USUARIO WHERE PK_ID_USUARIO = 1;
delete from CLIENTE WHERE PK_ID_USUARIO = 1;


INSERT INTO USUARIO (PK_ID_USUARIO, EMAIL, SENHA)
VALUES (1, 'admin@palacio', 'admin@palacio');

INSERT INTO CLIENTE(PK_ID_USUARIO)
VALUES (1);